### ISSUE TITLE
Local shortcuts

### ISSUE THREAD

**Issue by heyrict** [rfvgyhn/proton-usage#1]
This issue is opened in response to [the thread at reddit](https://www.reddit.com/r/linux_gaming/comments/qli9lx/protonusage_tool_to_list_steam_play_compatibility/).

Shortcuts are found in the file `~/.local/share/Steam/userdata/<your_id>/config/shortcut.vdf` in a binary format. i.e.

```
00000000: 0073 686f 7274 6375 7473 0000 3000 0261  .shortcuts..0..a
00000010: 7070 6964 0023 4cde 9401 4170 704e 616d  ppid.#L...AppNam
00000020: 6500 4d79 2074 696d 6520 6174 2070 6f72  e.My time at por
00000030: 7469 6100 0145 7865 0022 656e 7622 0001  tia..Exe."env"..
```

And here is the appid (2497596451, or 0x94de4c23) that stored in hex: 7070 6964 **0023 4cde 9401** 4170 704e 616d

There is a binary vdf parser [here](https://github.com/Corecii/steam-binary-vdf-ts) with a summarized spec for reference if you would like to implement a deserializer.

**Comment by rfvgyhn** [comment]
Perfect. Thanks.

**Comment by rfvgyhn** [comment]
b7011d1 implements shortcuts files.
