### ISSUE TITLE
Results appearing for uninstalled games

### ISSUE THREAD

**Issue by yochananmarqos** [rfvgyhn/proton-usage#2]
```
Proton-6.10-GE-1
    Fallout 76
Proton-6.14-GE-2
    Daymare: 1998 Demo
    The Elder Scrolls V: Skyrim Special Edition
Proton-6.16-GE-1
    ECHO
    Unknown (Id: 2888503496)
proton_5
    Resident Evil 0
    Resident Evil
    Unknown (Id: 2742054580)
proton_63
    Unknown (Id: 0)
    Unknown (Id: 2846825709)
```

Fallout76, Daymare and ECHO are not installed.

**Comment by rfvgyhn** [comment]
That's by design. Showing install/shortcut status is a feature that's coming. You can still uncheck the "Force the use of a specific Steam Play compatibility tool" when the game isn't installed though.

**Comment by yochananmarqos** [comment]
I'm using the default Proton 6.3-7 for Skyrim, but it's listed under Proton-6.14-GE-2 which isn't even installed. I have Proton-6.20-GE-1 installed.

What are the Unknown ID's?

**Comment by rfvgyhn** [comment]
Not sure why Skyrim is listed under the wrong version. If you open `~/.steam/root/config/config.vdf` and look in the `CompatToolMapping` section, what's the value for the `name` key under Skyrim's ID (489830)?

ID 0 is the version of proton you have set as the default. I just haven't gotten around to removing it from the list. The others are likely non-steam shortcuts. The code is there to get shortcut names, but that was a recent addition (#1) that hasn't yet been included in a new release.

**Comment by yochananmarqos** [comment]
Strange, it does indeed agree. I wonder if it's because I haven't launched it since then.

```
					"489830"
					{
						"name"		"Proton-6.14-GE-2"
						"config"		""
						"Priority"		"250"
					}
```

**Comment by yochananmarqos** [comment]
It turns out since I updated Proton-GE and removed the old version, I hadn't selected the new version yet. The output is correct now.
